//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGIUnimage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGIProductAvailableOS
    {
        public int ProductAvailableID { get; set; }
        public Nullable<short> ScenarioID { get; set; }
        public Nullable<int> CollectionID { get; set; }
        public int ProductID { get; set; }
        public int ProductColorID { get; set; }
        public int ProductDimID { get; set; }
        public int ProductCatID { get; set; }
        public Nullable<short> SizeOrder { get; set; }
        public int ColorID { get; set; }
        public int DimID { get; set; }
        public int CatID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public Nullable<int> ProductSubGroupID { get; set; }
        public double QtyAvailable { get; set; }
        public double QtyOrdered { get; set; }
        public Nullable<short> CreatedByUserID { get; set; }
        public Nullable<short> ModifiedByUserID { get; set; }
        public Nullable<short> DeletedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
